parse_config:
  raw_binding_map:
    '&kp LC(A)': $$mdi:select-all$$
    '&kp LC(X)': $$mdi:content-cut$$
    '&kp LC(C)': $$mdi:content-copy$$
    '&kp LC(V)': $$mdi:content-paste$$
    '&kp LC(LS(V))':
      tap: $$mdi:content-paste$$
      shifted: $$mdi:star$$
      type: side_by_side
    '&kp LC(Z)': $$mdi:undo$$
    '&kp LC(LS(Z))': $$mdi:redo$$
    '&kp LG(ESC)': $$mdi:lock-outline$$
    '&kp LG(LS(S))': $$mdi:power-sleep$$
    '&kp LG(LS(P))': $$mdi:power$$
    '&kp LG(N1)':
      tap: $$mdi:eye$$
      shifted: '1'
      type: side_by_side
    '&kp LG(N2)':
      tap: $$mdi:eye$$
      shifted: '2'
      type: side_by_side
    '&kp LG(N3)':
      tap: $$mdi:eye$$
      shifted: '3'
      type: side_by_side
    '&kp LG(N4)':
      tap: $$mdi:eye$$
      shifted: '4'
      type: side_by_side
    '&kp LG(N5)':
      tap: $$mdi:eye$$
      shifted: '5'
      type: side_by_side
    '&kp LG(N6)':
      tap: $$mdi:eye$$
      shifted: '6'
      type: side_by_side
    '&kp LG(N7)':
      tap: $$mdi:eye$$
      shifted: '7'
      type: side_by_side
    '&kp LG(N8)':
      tap: $$mdi:eye$$
      shifted: '8'
      type: side_by_side
    '&kp LG(N9)':
      tap: $$mdi:eye$$
      shifted: '9'
      type: side_by_side
    '&kp LG(UP)':
      tap: $$mdi:eye$$
      shifted: $$mdi:arrow-up$$
      type: side_by_side
    '&kp LG(DOWN)':
      tap: $$mdi:eye$$
      shifted: $$mdi:arrow-down$$
      type: side_by_side
    '&kp LG(LEFT)':
      tap: $$mdi:eye$$
      shifted: $$mdi:arrow-left$$
      type: side_by_side
    '&kp LG(RIGHT)':
      tap: $$mdi:eye$$
      shifted: $$mdi:arrow-right$$
      type: side_by_side
    '&kp LG(LS(N1))':
      tap: $$mdi:application-outline$$
      shifted: '1'
      type: side_by_side
    '&kp LG(LS(N2))':
      tap: $$mdi:application-outline$$
      shifted: '2'
      type: side_by_side
    '&kp LG(LS(N3))':
      tap: $$mdi:application-outline$$
      shifted: '3'
      type: side_by_side
    '&kp LG(LS(N4))':
      tap: $$mdi:application-outline$$
      shifted: '4'
      type: side_by_side
    '&kp LG(LS(N5))':
      tap: $$mdi:application-outline$$
      shifted: '5'
      type: side_by_side
    '&kp LG(LS(N6))':
      tap: $$mdi:application-outline$$
      shifted: '6'
      type: side_by_side
    '&kp LG(LS(N7))':
      tap: $$mdi:application-outline$$
      shifted: '7'
      type: side_by_side
    '&kp LG(LS(N8))':
      tap: $$mdi:application-outline$$
      shifted: '8'
      type: side_by_side
    '&kp LG(LS(N9))':
      tap: $$mdi:application-outline$$
      shifted: '9'
      type: side_by_side
    '&kp LG(LS(UP))':
      tap: $$mdi:application-outline$$
      shifted: $$mdi:arrow-up$$
      type: side_by_side
    '&kp LG(LS(DOWN))':
      tap: $$mdi:application-outline$$
      shifted: $$mdi:arrow-down$$
      type: side_by_side
    '&kp LG(LS(LEFT))':
      tap: $$mdi:application-outline$$
      shifted: $$mdi:arrow-left$$
      type: side_by_side
    '&kp LG(LS(RIGHT))':
      tap: $$mdi:application-outline$$
      shifted: $$mdi:arrow-right$$
      type: side_by_side
    '&kp LC(T)': $$mdi:tab-plus$$
    '&kp LC(F4)': $$mdi:tab-remove$$
    '&kp LC(PGUP)':
      tap: $$mdi:tab$$
      shifted: $$mdi:arrow-left$$
      type: side_by_side
    '&kp LC(PGDN)':
      tap: $$mdi:tab$$
      shifted: $$mdi:arrow-right$$
      type: side_by_side
    '&kp LC(LS(PGUP))':
      tap: $$mdi:tab$$
      shifted: $$mdi:chevron-double-left$$
      type: side_by_side
    '&kp LC(LS(PGDN))':
      tap: $$mdi:tab$$
      shifted: $$mdi:chevron-double-right$$
      type: side_by_side
    '&kp LG(LS(Q))':
      tap: $$mdi:application-outline$$
      shifted: $$mdi:close$$
      type: side_by_side
    '&kp LG(LS(ENTER))':
      tap: $$mdi:google-chrome$$
      shifted: $$mdi:plus$$
      type: side_by_side
    '&kp LA(LEFT)':
      tap: $$mdi:google-chrome$$
      shifted: $$mdi:step-backward$$
      type: side_by_side
    '&kp LA(RIGHT)':
      tap: $$mdi:google-chrome$$
      shifted: $$mdi:step-forward$$
      type: side_by_side
    '&kp LC(LS(R))':
      tap: $$mdi:google-chrome$$
      shifted: $$mdi:reload$$
      type: side_by_side
    '&kp LC(I)':
      tap: $$mdi:google-chrome$$
      shifted: $$mdi:cloud-search-outline$$
      type: side_by_side
    '&kp LC(LS(N))':
      tap: $$mdi:google-chrome$$
      shifted: $$mdi:incognito$$
      type: side_by_side
    '&kp LC(LS(T))':
      tap: $$mdi:tab$$
      shifted: $$mdi:undo$$
      type: side_by_side
    '&kp LG(ENTER)':
      tap: $$mdi:console-line$$
      shifted: $$mdi:plus$$
      type: side_by_side
    '&kp LC(LS(C))':
      tap: $$mdi:console-line$$
      shifted: $$mdi:content-copy$$
      type: side_by_side
    '&kp LC(LS(COMMA))':
      tap: $$mdi:console-line$$
      shifted: $$mdi:arrow-up$$
      type: side_by_side
    '&kp LC(LS(DOT))':
      tap: $$mdi:console-line$$
      shifted: $$mdi:arrow-down$$
      type: side_by_side
    '&kp LC(LS(END))':
      tap: $$mdi:console-line$$
      shifted: $$mdi:arrow-collapse-down$$
      type: side_by_side
    '&kp LC(LS(H))':
      tap: $$mdi:console-line$$
      shifted: $$mdi:script-outline$$
      type: side_by_side

  zmk_preamble: '#define KEYMAP_OS_LINUX'
